//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KRS.rc
//
#define IDC_BUTTON_CHANGE               3
#define IDC_LOAD_CONFIG                 3
#define IDC_BUTTON_RESET                3
#define IDC_BUTTON_SAVE                 4
#define IDC_BUTTON_CLEAR                5
#define IDD_ABOUTBOX                    100
#define IDD_KRS_FORM                    101
#define IDD_DIALOG_CALIBR               102
#define IDD_CEMENTVIEW                  103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_DBVIEW                      106
#define IDD_MAINVIEW                    108
#define IDD_DLGPASSWORD                 109
#define PM_SETSPLITPARAM                110
#define ID_ORIENT_VIEW                  112
#define ID_PROP_INIT                    127
#define IDR_MAINFRAME                   128
#define IDR_KRSREALTIMETYPE             129
#define IDR_KRSTYPE                     130
#define IDD_DIALOG_PANEL0               130
#define IDD_DIALOG_PANEL_H              131
#define IDD_DIALOG_LINE_PARAM           132
#define IDC_CURSOR1                     133
#define IDD_DIALOG_CHANGE_PARAM         134
#define IDD_DIALOG_ADD_PARAM            135
#define IDI_ICON_DOWN                   136
#define IDI_ICON_UP                     137
#define IDD_DIALOG_NAME_PANEL           138
#define IDD_DIALOG_BAR_DB               139
#define IDD_INIT_PROP_DOL               140
#define IDD_DIALOG_NET                  141
#define IDD_DIALOG_DEF_DB               142
#define IDD_DIALOG_KALIBROVKA           143
#define IDD_DIALOG_SELECT_CALIBR_PARAM  144
#define IDD_DIALOG_SELECT_CHANNEL       144
#define IDD_DIALOG_MAP_PARAM            145
#define IDD_DIALOG_NEW_CORRESPONDENCE   146
#define IDD_FORMULA_EDITOR              149
#define IDD_DIALOG_EDIT_FORMULA         149
#define IDD_DIALOG_ARG_CONST            151
#define IDD_DIALOG_SELECT_MARKER_TYPE   152
#define IDD_DIALOG_EDIT_MARKER_TYPE     153
#define IDD_DIALOG_WAITING              154
#define IDR_MENU_CONT                   155
#define IDD_DIALOG_CONFIG_DEVICES       156
#define IDB_BITMAP_CHANNEL              158
#define IDB_BITMAP_DEVICE               159
#define IDD_DIALOG_EDIT_DEVICE          160
#define IDB_BITMAP_CFG                  160
#define IDD_DIALOG_EDIT_SENSOR          163
#define IDC_CURSOR2                     168
#define IDD_DIALOG_DEBUG                169
#define IDD_INIT_CIRCULIACIYA           170
#define IDD_DIALOG_SETTINGS_BO          171
#define IDD_DIALOG_EDIT_TEXT            173
#define IDI_ICON_ADD_PARAM              174
#define IDI_ICON_PLUS                   175
#define IDI_ICON_MINUS                  176
#define IDD_INIT_PROP_ADD               187
#define IDD_DIALOG_FORMULAS_LIST        189
#define IDD_DIALOG_SETTINGS_BO_OLD      190
#define IDD_DIALOG_EDIT_BO              191
#define IDD_DIALOG_EDIT_DE              192
#define IDD_DIALOG_ARG_PIECEWISE        194
#define IDI_ICON_DOWN2                  195
#define IDI_ICON_UP2                    196
#define IDD_DIALOG_STAGE_SETTINGS       197
#define IDD_DIALOG_EDIT_CALCULATION     198
#define IDI_ICON_REMOVE                 199
#define IDI_ICON_REMOVE_MENU            200
#define IDI_ICON_REMOVE_INACTIVE        201
#define IDD_DIALOG_DIGITAL_PANNEL_SETTINGS 202
#define IDI_ICON_MINUS1                 202
#define IDI_ICON_KEEP                   202
#define IDD_DIALOG_MEM                  203
#define IDR_KRSRARCHIVETYPE1            203
#define IDD_DIALOG_HARD_CFG             204
#define IDD_DIALOG1                     205
#define IDD_DIALOG_CHANGEORDERLIST      205
#define IDD_DIALOG_CALIBR_NEW           206
#define IDD_INIT_ROTOR                  208
#define IDD_DIALOG_STAGES_LIB           209
#define IDD_DIALOG_ADD_STAGE            211
#define IDD_ADM                         212
#define IDD_DIALOG_BAR_CEMENT           213
#define IDD_DIALOG2                     214
#define IDD_DIALOG_PANEL_CEMENT         214
#define IDD_INTERFACE                   217
#define IDD_DIALOG_MODULES_EXTERNAL     219
#define IDI_ICON_START                  223
#define IDD_DIALOG_WORK                 224
#define IDD_DIALOG_WAIT_DB              225
#define IDD_DIALOG_OPISANIE_PROEKTA     226
#define IDD_DIALOG_COLOR_INTERFACE      227
#define IDD_DIALOG_SELECTDATA           230
#define IDD_DIALOG_JOURNAL              232
#define IDD_DIALOG_SELECTDATADAY        238
#define IDD_INIT_PROP_MOMENT            239
#define IDD_INIT_PROP_KVADRAT           240
#define IDD_INIT_PROP_VES               241
#define IDD_INIT_PROP_DAVLENIE          242
#define IDD_INIT_PROP_KNBK              243
#define IDD_INIT_PROP_IZABOI            244
#define IDD_INIT_PROP_TALBLOK           245
#define IDR_KRSRARCHIVETYPE             250
#define IDR_KRSCEMENTTYPE               252
#define IDI_ICON_STOP                   253
#define IDC_RADIO_SCALE_GLUB            1005
#define IDC_CHECK_SERV                  1005
#define IDC_STATIC_Wk                   1006
#define IDC_CHECK_CONV                  1006
#define IDC_RADIO_SCALE_TIM             1007
#define IDC_CHECK_DB                    1007
#define IDC_BUTTON_GET_PARAM            1008
#define IDC_STATIC_NKBK                 1008
#define IDC_BUTTON_DELETE_PARAM         1009
#define IDC_EDIT_PHYS                   1009
#define IDC_STATIC_NULL2                1010
#define IDC_STATIC_MU                   1010
#define IDC_STATIC_DELTA_TB             1010
#define IDC_STATIC_NULL3                1011
#define IDC_BUTTON_COLOR_PARAM          1011
#define IDC_BUTTON_SET                  1011
#define IDC_STATIC_WAIT_MSG             1012
#define IDC_STATIC_MU2                  1013
#define IDC_STATIC_CURR_VAL             1014
#define IDC_EDIT_THICK_LINE             1015
#define IDC_LIST_TABLE                  1015
#define IDC_STATIC_THIK_LINE            1016
#define IDC_BUTTON_RELOAD               1016
#define IDC_STATIC_THICK_TEXT           1016
#define IDC_RADIO_ARCHIVE               1017
#define IDC_STATIC_NAME_PAR             1017
#define IDC_SAVE_TABLE                  1017
#define IDC_BUTTON_ADD                  1017
#define IDC_STATIC_DIGITS_TEXT          1017
#define IDC_RADIO_REAL_TIME             1018
#define IDC_BUTTON_ZERO                 1018
#define IDC_BUTTON_DELETE               1018
#define IDC_STATIC_COLOR                1018
#define IDC_BUTTON_KEEP                 1018
#define IDC_RADIO_OTCHET                1019
#define IDC_STATIC_CURR_ADSP            1019
#define IDC_BUTTON_DELETE2              1019
#define IDC_BUTTON_COPY                 1019
#define IDC_STATIC_DB_TIME_INTERVAL     1019
#define IDC_RADIO_NGR1                  1020
#define IDC_EDIT_STARTTIME              1020
#define IDC_BUTTON_ADD_SENSOR           1020
#define IDC_STATIC_THICK_LINE           1020
#define IDC_BUTTON_CHOOSE_FONT          1020
#define IDC_RADIO_CEMENT                1020
#define IDC_RADIO_NGR2                  1021
#define IDC_LIST_ADD_PARAM              1021
#define IDC_EDIT_DIAPAZONTIME           1021
#define IDC_STATIC_DIGITS               1021
#define IDC_RADIO_NGR3                  1022
#define IDC_BUTTON_NAME_PANEL           1022
#define IDC_STATIC_DB_VAL_INTERVAL      1022
#define IDC_BUTTON_WK__MINUS            1023
#define IDC_EDIT_NAME_PANEL             1023
#define IDC_STATIC_NAME_PANEL           1024
#define IDC_BUTTON_EXCEL                1025
#define IDC_EDIT_DAVLENIE_AVARIA        1026
#define IDC_EDIT_DAVLENIE_BLOK          1027
#define IDC_EDIT_DAVLENIE_MIN           1028
#define IDC_EDIT_DOL_BLOK               1028
#define IDC_EDIT_DOL_MAX                1029
#define IDC_BUTTON_WK__PLUS             1030
#define IDC_COMBO_VES_DIAPAZON          1030
#define IDC_EDIT_VES_AVARIA             1031
#define IDC_BUTTON_NULL                 1032
#define IDC_EDIT_VES_BLOK               1032
#define IDC_COMBO_KVADRAT_PEREVODNIK    1032
#define IDC_BUTTON_NULL2_MINUS          1033
#define IDC_EDIT_KVADRAT_DLINA          1033
#define IDC_BUTTON_NULL2_PLUS           1034
#define IDC_COMBO_KVADRAT_ELEVATOR      1034
#define IDC_BUTTON_KNBK                 1035
#define IDC_EDIT_KNBK_PATH              1035
#define IDC_EDIT_KVADRAT_PEREVODNIK     1035
#define IDC_BUTTON_LBT_MINUS            1036
#define IDC_BUTTON_KNBK_SELECT_PATH     1036
#define IDC_EDIT_KVADRAT_DLINA3         1036
#define IDC_EDIT_KVADRAT_ELEVATOR       1036
#define IDC_BUTTON_LBT_PLUS             1037
#define IDC_BUTTON_KNBK_OPEN            1037
#define IDC_EDIT_KNBK_NUMELEMENT        1038
#define IDC_BUTTON_LBT_PLUS2            1038
#define IDC_EDIT_KNBK_KOMPONOVKA        1039
#define IDC_EDIT_KNBK_NUMLIST           1040
#define IDC_EDIT_TALBLOK_AVARIA         1041
#define IDC_COMBO_TALBLOK_DIAPAZON      1042
#define IDC_EDIT_IZABOI_VALUE           1043
#define IDC_BUTTON_REFRESH              1044
#define IDC_EDIT_NULL3                  1045
#define IDC_EDIT_POROG_BUR              1045
#define IDC_EDIT_PATH_DB                1046
#define IDC_EDIT_PORT_DB                1047
#define IDC_EDIT_PATH_SERVER            1048
#define IDC_EDIT_NANE_SERVER_DB         1048
#define IDC_EDIT_PORT_SERVER            1049
#define IDC_EDIT_NAME_DB                1049
#define IDC_EDIT_PATH_KONV              1050
#define IDC_EDIT_NAME_USER_DB           1050
#define IDC_EDIT_PORT_KONV              1051
#define IDC_EDIT_PASSWD_DB              1051
#define IDC_BUTTON_NEW_DB               1052
#define IDC_IND_SERV                    1056
#define IDC_IND_WEIGHT                  1057
#define IDC_IND_CONV                    1058
#define IDC_IND_DB                      1059
#define IDC_IND_PRESSURE                1060
#define IDC_EDIT_SSS                    1061
#define IDC_IND_LOAD                    1061
#define IDC_IND_SHURF                   1062
#define IDC_STATIC_NAME_I_ZABOY         1066
#define IDC_STATIC_NAME_TBLOCK          1067
#define IDC_EDIT_PARAM_NAME             1069
#define IDC_EDIT_MOMENT_MAX_LEVEL       1069
#define IDC_BUTTON_CHOOSE               1070
#define IDC_RADIO_MOMENT_DIAPAZON_30    1070
#define IDC_RADIO_MOMENT_DIAPAZON       1070
#define IDC_EDIT_PARAM_NUM              1071
#define IDC_RADIO_MOMENT_DIAPAZON_60    1071
#define IDC_RADIO_NA_PULT_MOMENT_NA_INSTRUMENTE 1072
#define IDC_EDIT_MU                     1072
#define IDC_RADIO_NA_PULT_MOMENT        1072
#define IDC_RADIO_NA_PULT_MOMENT_NA_ROTORE 1073
#define IDC_EDIT_MIN_VAL                1073
#define IDC_RADIO_MOMENT_NA_PULT_60     1074
#define IDC_BUTTON_BROWSE1              1074
#define IDC_RADIO_MOMENT_NA_PULT_DIAPAZON 1074
#define IDC_RADIO_MOMENT_NA_PULT_30     1075
#define IDC_BUTTON_BROWSE2              1075
#define IDC_RADIO_MOMENT_NA_PULT_15     1076
#define IDC_EDIT_MAX_VAL                1076
#define IDC_RADIO_MOMENT_NA_PULT_9      1077
#define IDC_CHECK_CONTROL               1077
#define IDC_EDIT_PARAM_NAME_GRF         1077
#define IDC_EDIT_CHANNEL                1078
#define IDC_STATIC_FILE1                1079
#define IDC_EDIT_FILE1                  1079
#define IDC_STATIC_FILE2                1080
#define IDC_EDIT_FILE2                  1080
#define IDC_BUTTON_CHOOSE_NOTHING       1081
#define IDC_CHECK_ACTIVE                1082
#define IDC_EDIT_BLOCK_VAL              1083
#define IDC_EDIT_CRUSH_VAL              1084
#define IDC_BUTTON_BROWSE3              1085
#define IDC_EDIT_FILE3                  1086
#define IDC_EDIT_MIN_GR_VAL             1087
#define IDC_EDIT_MAX_GR_VAL             1088
#define IDC_COMBO_CONTROL_TYPE          1089
#define IDC_EDIT_FORMULA_VIEW           1090
#define IDC_BUTTON_CHOOSE_ATTR          1090
#define IDC_COMBO_ARG_NUM               1091
#define IDC_BUTTON_CHOOSE_NOTHING_ATTR  1091
#define IDC_COMBO_ARG_TYPE              1092
#define IDC_EDIT_CHANNEL_ATTR           1092
#define IDC_EDIT_RESULT_VIEW            1093
#define IDC_EDIT_PARAM_NAME_GRF2        1093
#define IDC_EDIT_TIME_AVERAGE           1093
#define IDC_EDIT_CONST                  1094
#define IDC_EDIT_TEMPLATE_VIEW          1094
#define IDC_EDIT_DB_TIME_INTERVAL       1094
#define IDC_STATIC_GRAPH_AREA           1095
#define IDC_EDIT_MIN_VAL3               1095
#define IDC_EDIT_DB_VAL_INTERVAL        1095
#define IDC_BUTTON_CLEAR1               1096
#define IDC_STATIC_STAGE                1097
#define IDC_BUTTON_CLEAR2               1097
#define IDC_LIST_MARKER_TYPES           1098
#define IDC_BUTTON_CLEAR3               1098
#define IDC_BUTTON_SELECT               1100
#define IDC_EDIT_NAME                   1101
#define IDC_PROGRESS_BAR                1102
#define IDC_EDIT_TEXT_CENTERED          1102
#define IDC_EDIT_TIMEOUT                1102
#define IDC_EDIT_V0                     1102
#define IDC_BUTTON_STOP                 1103
#define IDC_EDIT_V1                     1103
#define IDC_EDIT_TEXT_RIGHT             1103
#define IDC_CHECK_NGR1                  1104
#define IDC_EDIT_JUMP_UP                1104
#define IDC_CHECK_NGR2                  1105
#define IDC_TREE_DEVICES                1105
#define IDC_EDIT_JUMP_DOWN              1105
#define IDC_CHECK_NGR3                  1106
#define IDC_BUTTON_EDIT                 1107
#define IDC_BUTTON_ADD_DEVICE           1108
#define IDC_EDIT_CURRENT_CONFIG         1109
#define IDC_SAVE_CONFIG                 1110
#define IDC_COMBO_ADDR                  1112
#define IDC_EDIT_DATA_OFFSET            1114
#define IDC_EDIT_DATA_LEN               1115
#define IDC_COMBO_POINT                 1116
#define IDC_EDIT_DSP1                   1116
#define IDC_EDIT_MEX_INTERVAL           1117
#define IDC_EDIT_DSP0                   1117
#define IDC_EDIT_MEX_INTERVAL2          1118
#define IDC_EDIT_TIME_CIRCULIACII_START 1118
#define IDC_EDIT_TIME_BURENIYA_START    1119
#define IDC_STATIC_REGIM_INDICATOR      1119
#define IDC_EDIT_POROG_MOMENT           1119
#define IDC_EDIT_POROG_TIME             1120
#define IDC_EDIT_MEX_INTERVAL4          1120
#define IDC_EDIT_VES_ROTOR_BUR          1120
#define IDC_EDIT_POROG_VISOTA           1121
#define IDC_STATIC_TEST                 1121
#define IDC_STATIC_TESTT                1122
#define IDC_EDIT_USTAVKA                1123
#define IDC_EDIT_LIMIT                  1124
#define IDC_EDIT_ADDR_BO1               1125
#define IDC_EDIT_ADDR_BO2               1126
#define IDC_EDIT_TEXT_LEFT              1131
#define IDC_BUTTON_MINUS                1132
#define IDC_BUTTON_PLUS                 1133
#define IDC_STATIC_COLOR_TEXT           1134
#define IDC_STATIC_INTERVAL_TEXT        1135
#define IDC_BUTTON_MINUS2               1135
#define IDC_TREE_CHANNELS               1136
#define IDC_BUTTON_PLUS2                1136
#define IDC_BUTTON1                     1139
#define IDC_BUTTON_BREAK_DB_REQUEST     1139
#define IDC_BUTTON_EDIT_FORMULA         1139
#define IDC_BUTTON_NEW_STAGE            1139
#define IDC_BUTTON_TOP                  1139
#define IDC_BUTTON_CFG                  1139
#define IDC_BUTTON_START_STOP           1139
#define IDC_BUTTON_ADD_M                1139
#define IDC_BUTTON_START_STAGE          1139
#define IDC_START_PAUSE_STAGE           1139
#define IDC_BUTTON_COLOR_INTERFACE      1139
#define IDC_BUTTON_RESET_DEFAULT        1139
#define IDC_MINUS_BO_TIME               1139
#define IDC_BUTTON_SET_GLX              1139
#define IDC_BUTTON2                     1140
#define IDC_BUTTON_MODULE_ADD           1140
#define IDC_BUTTON_EDIT_M               1140
#define IDC_MINUS_BO_TIME2              1140
#define IDC_PLUS_BO_TIME                1140
#define IDC_BUTTON_SET_GLX2             1140
#define IDC_BUTTON_SET_GLI              1140
#define IDC_IND_VALUE                   1141
#define IDC_RESTART_STAGE               1141
#define IDC_BUTTON_DELETE_M             1141
#define IDC_CHECK_USE_VOLTAGE           1142
#define IDC_FINISH_STAGE                1142
#define IDC_BUTTON_ADD_K                1142
#define IDC_STATIC_TIRE                 1143
#define IDC_BUTTON_EDIT_K               1143
#define IDC_CHECK_USE_VOLTAGE2          1143
#define IDC_CHECK_JUMPS                 1143
#define IDC_STATIC_DB_TEXT              1144
#define IDC_BUTTON_DELETE_K             1144
#define IDC_PROGRESS_DB                 1145
#define IDC_BUTTON_ADD_S                1145
#define IDC_EDIT_MESTOROGDENIE          1146
#define IDC_BUTTON_EDIT_S               1146
#define IDC_EDIT_KUST                   1147
#define IDC_STATIC_DB                   1147
#define IDC_BUTTON_DELETE_S             1147
#define IDC_EDIT_SKVAGINA               1148
#define IDC_STATIC_CONV                 1148
#define IDC_BUTTON_ADD_R                1148
#define IDC_EDIT_RABOTA                 1149
#define IDC_STATIC_SERV                 1149
#define IDC_BUTTON_EDIT_R               1149
#define IDC_STATIC_SEPARATOR1           1150
#define IDC_BUTTON_DELETE_R             1150
#define IDC_STATIC_SEPARATOR2           1151
#define IDC_STATIC_SEPARATOR3           1152
#define IDC_STATIC_SHURF                1153
#define IDC_STATIC_LOAD                 1154
#define IDC_STATIC_PRESSURE             1155
#define IDC_STATIC_WEIGHT               1156
#define IDC_STATIC_TIMER                1157
#define IDC_STATIC_BYTES                1158
#define IDC_LIST_FORMULAS               1159
#define IDC_STATIC_TIMER2               1160
#define IDC_LIST_ARGS                   1160
#define IDC_COMBO_PARAM_TYPE            1161
#define IDC_STATIC_CHANNEL              1162
#define IDC_STATIC_CHANNEL_ATTR         1163
#define IDC_LIST_BO                     1164
#define IDC_EDIT_DEV_ADDR               1165
#define IDC_STATIC_I_ZABOY              1166
#define IDC_LIST_DE                     1166
#define IDC_STATIC_TBLOCK               1167
#define IDC_COMBO_LENGTH                1167
#define IDC_EDIT_DEV_ADDR2              1167
#define IDC_EDIT_FORMULA                1168
#define IDC_EDIT_TEMPLATE               1169
#define IDC_EDIT_PRESET                 1169
#define IDC_CHECK_USTAVKA               1170
#define IDC_EDIT_USTAVKA_ADDR           1171
#define IDC_EDIT_LIMIT_ADDR             1172
#define IDC_STATIC_RECT                 1172
#define IDC_EDIT_IN_FORMULA             1173
#define IDC_EDIT_IN                     1174
#define IDC_LIST_PHASE                  1175
#define IDC_EDIT_OUT                    1175
#define IDC_LIST_STAGES                 1176
#define IDC_CHECK_VIEW_REPER            1179
#define IDC_EDIT1                       1180
#define IDC_EDIT_DAY                    1180
#define IDC_EDIT_SIGNAL                 1180
#define IDC_PASSWORD                    1180
#define IDC_EDIT_MODULE_PATH            1180
#define IDC_EDIT_SET_GLX                1180
#define IDC_CHECK_VIEW_PANEL_BUR        1181
#define IDC_EDIT_MONTH                  1181
#define IDC_EDIT_VALUE                  1181
#define IDC_EDIT_SET_GLI                1181
#define IDC_CHECK_VIEW_DAGN             1182
#define IDC_EDIT_YEAR                   1182
#define IDC_EDIT_SIGNAL_NOW             1182
#define IDC_CHECK_VIEW_DGT_RT           1183
#define IDC_EDIT_START_GLUB             1183
#define IDC_EDIT_VALUE_NOW              1183
#define IDC_CHECK_VIEW_DGT_BD           1184
#define IDC_PROGRESS_DEVICES            1184
#define IDC_EDIT_LEN_GLUB               1184
#define IDC_CHECK_VIEW_REAL_ARCH        1185
#define IDC_STATIC_DEVICE_INFO          1185
#define IDC_EDIT_HOUR                   1185
#define IDC_CHECK_VIEW_TIME_GLUB        1186
#define IDC_PROGRESS_MEMORY             1186
#define IDC_LIST_CFGS                   1186
#define IDC_EDIT_MIN                    1186
#define IDC_EDIT_MINUT                  1186
#define IDC_CHECK5                      1187
#define IDC_CHECK_VIEW_ETAP             1187
#define IDC_STATIC_DEVICE_INFO2         1187
#define IDC_STATIC_MEMORY_INFO          1187
#define IDC_CHECK6                      1188
#define IDC_CHECK_DATA_BEGEND           1188
#define IDC_LIST1                       1188
#define IDC_LIST_LOG                    1188
#define IDC_LIST_WORK                   1188
#define IDC_CHECK7                      1189
#define IDC_CHECK_STUPENKI              1189
#define IDC_CHECK8                      1190
#define IDC_CHECK_SCROLL_ALL            1190
#define IDC_IPADDRESS1                  1190
#define IDC_CHECK_PARAM_BUR             1191
#define IDC_STATIC_DAY                  1191
#define IDC_CHECK_HIGH_PANEL            1192
#define IDC_STATIC_MONTH                1192
#define IDC_CHECK_GRAPH_DIGIT           1193
#define IDC_STATIC_YEAR                 1193
#define IDC_CHECK_TIME                  1194
#define IDC_CHECK_DATA_TIME             1194
#define IDC_EDIT_INTERVAL_TIME          1194
#define IDC_STATIC_INTERVAL_TIME        1195
#define IDC_CHECK_DATA_TIME2            1195
#define IDC_CHECK_CONVERTER             1195
#define IDC_STATIC_START_GLUB           1196
#define IDC_CHECK_CONVERTER2            1196
#define IDC_CHECK_REGIME_BUR            1196
#define IDC_STATIC_MONTH2               1197
#define IDC_CHECK_SELECT_ONLY_Y         1197
#define IDC_BUTTON_DO_REQUEST           1198
#define IDC_RADIO_SELCT_TIMEGLUB        1199
#define IDC_STATIC_DAY2                 1200
#define IDC_STATIC_HOUR                 1200
#define IDC_LIST_ORDER                  1200
#define IDC_RADIO_SELCT_TIMEGLUB2       1201
#define IDC_BUTTON_DOWN                 1201
#define IDC_STATIC_GRAPH_POS            1202
#define IDC_EDIT_INTERVAL_MINUT         1202
#define IDC_STATIC_TABLE_POS            1203
#define IDC_STATIC_INTERVAL_TIME2       1203
#define IDC_RADIO1                      1204
#define IDC_STATIC_HOUR2                1204
#define IDC_RADIO2                      1205
#define IDC_EDIT_POROG_MOMENT_1         1205
#define IDC_RADIO3                      1206
#define IDC_EDIT_VES_ROTOR_BUR_1        1206
#define IDC_CHECK1                      1207
#define IDC_CHECK_ROTOR                 1207
#define IDC_CHECK_CALC_OUTER            1207
#define IDC_CHECK_RABOTA_BEZ_SHURFA     1207
#define IDC_CHECK_MAX                   1207
#define IDC_CHECK_EMPTY                 1207
#define IDC_CHECK_CALC_OUTER2           1208
#define IDC_CHECK_SCALE                 1208
#define IDC_LIST_LIB                    1208
#define IDC_CHECK_MIN                   1208
#define IDC_CHECK_MID                   1209
#define IDC_STATIC_WORK                 1210
#define IDC_CHECK_GRAPH                 1210
#define IDC_STATIC_WORK2                1211
#define IDC_STATIC_STAGES               1211
#define IDC_CHECK_MID2                  1211
#define IDC_CHECK_PRESET                1211
#define IDC_EDIT3                       1212
#define IDC_CHECK_USE_PARAM_SETTINGS    1212
#define IDC_STATIC_R                    1213
#define IDC_BUTTON_MODULE_DELETE        1214
#define IDC_EDITMODULE_NAME             1215
#define IDC_LIST2                       1216
#define IDC_LIST_MODULES                1216
#define IDC_BUTTON_MODULE_SELECT        1217
#define IDC_COMBO_GRAPH                 1218
#define IDC_COMBO_M                     1219
#define IDC_COMBO_K                     1220
#define IDC_SLIDER1                     1220
#define IDC_COMBO_S                     1221
#define IDC_STATIC_IP_CLIENT            1221
#define IDC_COMBO_R                     1222
#define IDC_STATIC_IP_DB                1222
#define IDC_STATIC_DB_NAME              1223
#define IDC_COMBO_MODE                  1223
#define IDC_COMBO_TEMPLATE              1223
#define IDC_STATIC_STATUS               1224
#define IDC_STATIC_COLOR_FIELDGRAPH     1228
#define IDC_STATIC_COLOR_GRF_DGT        1229
#define IDC_STATIC_COLOR_GRF_GREED      1230
#define IDC_STATIC_COLOR_PANEL_GRF      1231
#define IDC_STATIC_COLOR_PANEL_DGT      1232
#define IDC_COMBO_STYLE_GREED           1233
#define IDC_STATIC_COLOR_PANEL_DGT2     1234
#define IDC_STATIC_COLOR_GRF_DGT_BK     1234
#define IDC_STATIC_DB_MU                1234
#define IDC_STATIC_BO_TIME              1235
#define IDC_STATIC_VER                  1236
#define IDC_STATIC_SET_GLX              1237
#define IDC_STATIC_SET_GLX2             1238
#define IDC_BUTTON3                     1239
#define IDC_STATIC_TEMPLATE             1240
#define IDC_BUTTON_SELECTDAY            1566
#define IDC_BUTTON_ALERTAVARIA          1568
#define IDC_BUTTON_ALERTAMAX            1582
#define IDC_BUTTON_ALERTMIN             1588
#define IDC_BUTTON_SELECTFREE2          1593
#define IDC_BUTTON_ALERTALL             1594
#define IDC_BUTTON_OTCHET4              1599
#define IDC_BUTTON_OTCHETFREE2          1605
#define IDC_BUTTON_JRNLHELP             1606
#define IDC_DATETIMEPICKER1             1626
#define IDC_DATETIMEPICKER2             1628
#define IDC_LIST_JOURNAL                1630
#define ID_MENU_MODULE_EXTERNAL         2000
#define ID_MENU_MODULE_EXTERNAL_1       2001
#define ID_MENU_MODULE_EXTERNAL_2       2002
#define ID_MENU_MODULE_EXTERNAL_3       2003
#define ID_MENU_MODULE_EXTERNAL_4       2004
#define ID_MENU_MODULE_EXTERNAL_5       2005
#define ID_MENU_MODULE_EXTERNAL_6       2006
#define ID_MENU_MODULE_EXTERNAL_7       2007
#define ID_MENU_MODULE_EXTERNAL_8       2008
#define ID_MENU_MODULE_EXTERNAL_9       2009
#define IDC_PANEL_KNOPKI                4000
#define ID_START_PROPERTY               32771
#define ID_MENU_PROP_DB                 32772
#define ID_MENU_TCPIT                   32773
#define ID_KALIBROVKA                   32774
#define ID_KALIBROVKA_M                 32775
#define ID_PARAMETRY                    32776
#define ID_KANALY                       32778
#define ID_MARKER_TYPES                 32779
#define IDR_CONT_MENU_MARKER            32780
#define IDR_CONT_MENU_SCALEGRF          32781
#define ID_TEST_INDICATION              32782
#define R_CONT_MENU_SCALE_1             32783
#define R_CONT_MENU_SCALE_10            32784
#define R_CONT_MENU_SCALE_20            32785
#define R_CONT_MENU_SCALE_60            32786
#define R_CONT_MENU_SCALE_120           32787
#define R_CONT_MENU_SCALE_240           32788
#define R_CONT_MENU_SCALE_360           32789
#define R_CONT_MENU_SCALE_720           32790
#define R_CONT_MENU_SCALE_1440          32791
#define R_CONT_MENU_SCALE_2880          32792
#define ID_CONFIG_DEVICES               32793
#define ID_DEBUG_INFO                   32794
#define ID_BLOCK_OTOBRAZHENIYA          32795
#define NT_MENU_SCALE_9000              32796
#define R_CONT_MENU_SCALE_G_10          32797
#define R_CONT_MENU_SCALE_G_20          32798
#define R_CONT_MENU_SCALE_G_50          32799
#define R_CONT_MENU_SCALE_G_100         32800
#define R_CONT_MENU_SCALE_G_200         32801
#define R_CONT_MENU_SCALE_G_500         32802
#define R_CONT_MENU_SCALE_G_1000        32803
#define R_CONT_MENU_SCALE_G_2000        32804
#define R_CONT_MENU_SCALE_G_5000        32805
#define NT_MENU_SCALE_G_10000           32806
#define ID_STAGE_SETTINGS               32807
#define ID_32808                        32808
#define ID_32809                        32809
#define ID_SAVE_MEM                     32810
#define ID_RESTORE_MEM                  32811
#define ID_DOWNLOAD_MEM                 32812
#define ID_UPLOAD_MEM                   32813
#define ID_32814                        32814
#define R_CONT_MENU_SCALE_5             32815
#define IDC_STATIC_INDICATOR_DATATIME   32816
#define ID_32816                        32816
#define ID_32817                        32817
#define ID_STAGE_LIB                    32818
#define ID_STAGES_SEQ                   32819
#define ID_STAGES_LIB                   32820
#define ID_VIEW_PASSWD                  32821
#define ID_DISABLE_PASSWD               32822
#define ID_MENU_OPISANIE_MESTOROGDENIJA 32824
#define ID_MENU_INTERFACE               32825
#define ID_32826                        32826
#define ID_32827                        32827
#define ID_NASTROIKA_MODULES            32828
#define ID_32829                        32829
#define ID_CHOOSE_FONT                  32830
#define ID_STAGES_LOAD                  32832
#define ID_32833                        32833
#define ID_32834                        32834
#define ID_32835                        32835
#define ID_STAGES_START                 32836
#define ID_STAGES_BREAK                 32837
#define ID_32838                        32838
#define ID_STAGES_FINISH                32839
#define ID_STAGES_CHOOSE_FONT           32840
#define ID_STAGES_SAVE                  32841
#define ID_32842                        32842
#define ID_STAGES_NEXT                  32843
#define ID_32844                        32844
#define ID_STAGES_USE_AS_TEMPLATE       32845
#define ID_32846                        32846
#define ID_32847                        32847
#define ID_ETAP_PROJECT_NEW             32848
#define ID_ETAP_PROJECT_LOAD            32849
#define ID_32850                        32850
#define ID_STAGES_GET_FROM_DB           32851
#define ID_32852                        32852
#define ID_32853                        32853
#define ID_OPEN_WORK                    32854
#define ID_NEW_WORK                     32855
#define ID_32856                        32856
#define ID_IMPORT_WORK                  32857
#define ID_STAGES_FINISH_ALL            32858
#define ID_STAGES_RESTART_ALL           32859
#define ID_32860                        32860
#define ID_STAGES_RESET                 32861
#define ID_STAGES_RESTART               32862
#define ID_32863                        32863
#define ID_EDIT_PROJECT                 32864
#define ID_STAGES_CHOOSE_FONT_SEL       32865
#define ID_ACCELERATOR_COLOR_INTERFACE  32866
#define ID_ACCELERATOR32868             32868
#define ID_VIEW_PASSWD_USER             32868

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32870
#define _APS_NEXT_CONTROL_VALUE         1241
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
